In [1]:
#label processing
import glob
import re

def create_label_and_reference(label_file_name):
    labels={}
    refs={}
    with open(label_file_name,'r') as f:

        for line in f.readlines():

            tokens=line.split("\t")


            if any(i.isdigit() for i in tokens[0]) :     
                if any(i.isdigit() for i in tokens[1]):
                
                    labels[float(tokens[0])]=float(tokens[1].strip("\n"))
                else:
                    labels[float(tokens[0])]=float(-999999)
                refs[float(tokens[0])] = float(tokens[0].strip("\n"))
    print("create label done.")
    return labels,refs
     


In [2]:
import cv2
import random
import glob
import numpy as np
from sortedcontainers import SortedDict

def create_image_and_label(image_path,image_size):


    data_root=image_path
    dic,references=create_label_and_reference("label_summary.txt")
    

    path=data_root+'\*jpeg'
    filenames=glob.glob(path)
    
    random.shuffle(filenames)
    labels=[]
    datas=[]
    refs=[]
    count=0          
    for name in filenames:
        key_value=float(name.rsplit('_')[-1].strip(".jpeg"))
        if key_value in dic:
            labels.append((dic[key_value]))
            refs.append((references[key_value]))  
        else:
            res =  dic[min(dic.keys(), key = lambda key: abs(key-key_value))] 
            labels.append(res)
            pos=min(dic.keys(), key = lambda key: abs(key-key_value))
            refs.append(pos)
        datas.append(cv2.imread(name,cv2.IMREAD_COLOR))    

    datas=np.array(datas).reshape(-1,image_size,image_size,3)
    print("all done")
    return datas,labels,refs

%time datas,labels,refs=create_image_and_label("all",224)


create label done.
all done
Wall time: 18min 11s


In [10]:
print(labels[0],refs[0])

1.495272 10341.0


In [ ]:
#trying out pickle to save datas and labels
import pickle


pickle_out=open("datas.pickle","wb")
pickle.dump(datas,pickle_out)

pickle_out.close()

pickle_out=open("labels.pickle","wb")
pickle.dump(labels,pickle_out)

pickle_out.close()

pickle_out=open("refs.pickle","wb")
pickle.dump(refs,pickle_out)

pickle_out.close()






In [20]:
import matplotlib.pyplot as plt

pickle_in=open("datas.pickle","rb")
X=pickle.load(pickle_in)

pickle_in=open("labels.pickle","rb")
y=pickle.load(pickle_in)

print(X[0].shape)
print(len(y))


print(X[0])

(32, 32, 1)
62909
[[[131]
  [110]
  [112]
  ...
  [110]
  [ 73]
  [ 88]]

 [[ 69]
  [119]
  [ 81]
  ...
  [148]
  [107]
  [125]]

 [[168]
  [101]
  [154]
  ...
  [125]
  [120]
  [ 68]]

 ...

 [[110]
  [115]
  [147]
  ...
  [143]
  [124]
  [ 71]]

 [[139]
  [112]
  [160]
  ...
  [108]
  [125]
  [119]]

 [[ 96]
  [129]
  [ 92]
  ...
  [ 80]
  [120]
  [105]]]
